### ISSUE TITLE
could find the base addres

### ISSUE THREAD

**Issue by devakumetsu** [Kalamity/classMemory#1]
could you please put here an example of how to get the base addrees adn find by those offsets ?, i could make this to return the current value.

0x74
0x1c
"League of Legends.exe"+169C294      095F1480

thanks in advance.

**Comment by Kalamity** [comment]
#SingleInstance force
#Include <classMemory> ;Include the memory class from the lib folder

; Not required - Just checks if you copied the class correctly
if (_ClassMemory.__Class != "_ClassMemory")
    msgbox class memory not correctly installed. Or the (global class) variable "_ClassMemory" has been overwritten

; Create an object to read the games memory
; The process/game must be running.
; If the process closes/restarts, then you need to call this line again.... You can call it before every read if you really want.
mem := new _ClassMemory("ahk_exe League of Legends.exe", "", hProcessCopy) 

;not required, but If it fails get the reason why
if !isObject(mem) 
{
    msgbox failed to open a handle
    if (hProcessCopy = 0)
        msgbox The program isn't running (not found) or you passed an incorrect program identifier parameter. 
    else if (hProcessCopy = "")
        msgbox OpenProcess failed. If the target process has admin rights, then the script also needs to be ran as admin. Consult A_LastError for more information.
    ExitApp
}

; not required, but makes it easier to read base address
; just double check the base address matches CE base address
SetFormat, integerfast, H 

msgbox % mem.BaseAddress 

SetFormat, integerfast, D 

; Reading a pointer with a final type of Float 
msgbox % mem.read(mem.BaseAddress + 0x169C294, "Float", 0x1C, 0x74)
