### ISSUE TITLE
processPatternScan always returning -1 (VirtualQueryEx() failed)

### ISSUE THREAD

**Issue by Plathix** [Kalamity/classMemory#3]
I'm trying to perform an AOB scan on the entire process memory of Brawlhalla. Every time I run the scan, it returns -1. I've tried running this in 32 and 64 bit, running it as administrator and not. I've even tried it on different programs, but it still just returns -1. I've skimmed the comments in the classMemory script but can't figure this out. Am I doing something wrong?

Here's my code:

```#include classMemory.ahk

brawlhalla := new _ClassMemory("ahk_exe Brawlhalla.exe", "", hProcessCopy)

if !isObject(brawlhalla)
{
	msgbox failed to open a handle
        if (hProcessCopy = 0)
        	msgbox The program isn't running (not found) or you passed an incorrect program identifier parameter. In some cases _ClassMemory.setSeDebugPrivilege() may be required. 
        else if (hProcessCopy = "")
        	msgbox OpenProcess failed. If the target process has admin rights, then the script also needs to be ran as admin. _ClassMemory.setSeDebugPrivilege() may also be required. Consult A_LastError for more information.
        ExitApp
}

msgbox % brawlhalla.BaseAddress

pattern := ["?", 0x00, 0x00, 0x00, "?", "?", "?", 0x5C, 0x13, 0x52, 0x1A, 0x5A, 0x01, 0x00, 0x00, 0x00]

address := brawlhalla.processPatternScan(,,pattern*)

msgbox % address

**Comment by Plathix** [comment]
I've solved my issue. It turns out that I had the pattern wrong. After an update to the game in question, one of the bytes changed. I adjusted my AOB pattern accordingly and it worked.

**Comment by Zayoe4** [comment]
@Plathix I am also trying to scan Brawlhalla, if I may ask, where were you getting you're AOB's?
