### ISSUE TITLE
Problem with reading values

### ISSUE THREAD

**Issue by ghost** [Kalamity/classMemory#4]
For some reason its reading values from certain addresses as 4bytes long... even when the type is Int64

block_id := mem.read(xy, "Int64")
 
For this address 1ea5b56ffc3 the value is 0x1622ff even though it should be 0x00000000001622FF
And for this address it works fine and is 8bytes long 1ea5b570053 and the value is 0x010000000E125AFF

**Comment by Kalamity** [comment]
Hi mate,
I don't really understand the problem.
0x1622ff is equal to 0x00000000001622FF - they are the same number. Leading zeroes are never shown.

**Comment by ghost** [comment]
I need them to show is that possible?

Also im pretty sure it sometimes shows the leading zeroes and sometimes it doesnt.

**Comment by Kalamity** [comment]
This isn't anything to do with the class.
The number is stored/read as a numerical value like any other - it's just how AHK itself is displaying it. There are various settings in AHK which impact this.

How are you converting the number to HEX - that is, how are you getting the script to output the value as 0x1622ff  & 0x010000000E125AFF?

**Comment by Kalamity** [comment]
If you just want them padded to a certain length, then you can use a function like this:
```
msgbox % clipboard := hexPad(0, "Int64")        ; --> 0x0000000000000000
msgbox % clipboard := hexPad(0x1622ff, "Int64") ; --> 0x00000000001622FF

; 0x1622ff hex = 1450751 dec
msgbox % clipboard := hexPad(1450751, "Int64")  ; --> 0x00000000001622FF
msgbox % clipboard := hexPad(1450751, "UInt")   ; -->         0x001622FF

return 

hexPad(numberIntOrHex, type := "UInt")
{
    static width := {   "UChar":    2,      "Char":    2   
                            , "UShort":  4,     "Short":    4   
                            ,   "UInt":  8,     "Int":      8   
                            ,   "Int64": 16}

    if !width.haskey(type)
        throw Exception(A_ThisFunc "() - Type '" type "' not found.", -1) 
    return format("0x{:0" width[type] "X}", numberIntOrHex)
}
```

**Comment by ghost** [comment]
Dude tysm for help i got it working ur the best really 😄 
Btw u should add this function to the classMemory because its really useful.
